### ISSUE TITLE
"TRUE "

### ISSUE THREAD

**Issue by sanket-naik-zocdoc** [thenativeweb/boolean#2]
Nice package. However, I was testing this package for my test cases and if failed for "TRUE " or "true ". trim might be required.

**Comment by goloroden** [comment]
Hey, thanks for reporting this issue … I will have a quick look at it.

**Comment by sanket-naik-zocdoc** [comment]
sure, thanks

**Comment by goloroden** [comment]
I'll be back in a few minutes…

**Comment by goloroden** [comment]
Ahhhh, I see … your string contains a whitespace in the end, right?

**Comment by sanket-naik-zocdoc** [comment]
yes.

**Comment by goloroden** [comment]
I've fixed it. I have added trimming for strings, and published a new version: `0.1.2`

Could you please verify whether this works for you? If so, I would like to close this issue.

**Comment by sanket-naik-zocdoc** [comment]
sure would do that

**Comment by sanket-naik-zocdoc** [comment]
verified.. all looks good. Closing the issue. Thanks for the quick turnaround
