### ISSUE TITLE
Support Node.js version v8

### ISSUE THREAD

**Issue by gajus** [thenativeweb/boolean#21]
There is really no reason to drop v8 support over a single line of code:

https://github.com/thenativeweb/boolean/blob/master/lib/boolean.ts#L3

It creates compatibility issues such as this:

https://github.com/gajus/roarr/issues/25

v8 is still Maintenance LTS.

**Comment by goloroden** [comment]
@gajus Thanks for bringing up this issue!

Our policy is to support only the latest LTS (i.e., starting from today, Node.js 12.x). 

If you need Node.js 8 support, please fork this repository. 

Please note that it’s not just a single line, as e.g. the build tool (which we use in all our repositories) requires Node.js 12.10 or above.

**Comment by goloroden** [comment]
PS: Node 8 LTS will be end of life on December 31st, 2019. See https://github.com/nodejs/Release#release-schedule for details.
