### ISSUE TITLE
SyntaxError using create-react-app and Node v13

### ISSUE THREAD

**Issue by gajus** [thenativeweb/boolean#25]
```
Failed to compile.

./node_modules/boolean/build/lib/boolean.js
SyntaxError: /Users/gajus/dev/applaudience/applaudience-explorer-web-app/node_modules/boolean/build/lib/boolean.js: Expected atom at position 2
    ^(?<truthy>t
      ^
^C

```

**Comment by gajus** [comment]
```
$ node -v                                                                   20:33:36
v13.0.0

```

**Comment by gajus** [comment]
Appears to be related https://github.com/babel/babel/issues/8951

**Comment by yeldiRium** [comment]
Hi gajus!

We don't use babel anymore and our code is transpiled from TypeScript. That might cause issues with babel which we don't account for.
I've tested the current release with node v13.0.1 (and node v12.13.0) and had no issues. If you can find a solution (or if the folks at babel do) we'd be happy to hear it, but for now we won't try to fix it.

Good luck ^.^

**Comment by goloroden** [comment]
Same here… I've tried to reproduce it as well, and it runs perfectly as-is on Node.js 13.0.1.

So, the issue seems to have another cause. Maybe, as you @gajus suggested, it's actually related to Babel.

**Comment by gajus** [comment]
For anyone else coming across this issue, this solution works.

https://github.com/babel/babel/issues/8951#issuecomment-508045524

As for the authors of the repository, compromising on library's compatibility for literally no reason, it is a quick and easy way to use trust of your users. All it takes to avoid this nonsense is changing:

```js
- return /^(?<truthy>true|t|yes|y|on|1)$/iu.test(value.trim());
+ return /^(true|t|yes|y|on|1)$/iu.test(value.trim());

```

I for one strip `boolean` out of my projects and not recommend anyone to use it.

**Comment by goloroden** [comment]
> As for the authors of the repository, compromising on library's compatibility for literally no reason

@gajus As already explained in #21, Node 8 will be EOL in December 2019, so we don't take any responsiblity for this any more.

> I for one will strip boolean out of my projects and not recommend anyone to use it.

Feel free to do so, that's how the open-source world works. If something is fine for you, great, if not, don't use it. You are not forced to use it, and sorry if you are disappointed by now, but we provide lots of code for free, and you're not paying us for that, so we're not responsible to provide any support beyond what we see as acceptable.

If you don't like that, feel free to fork it or use something else.

**Comment by goloroden** [comment]
PS: https://twitter.com/goloroden/status/1187470118936170496 and https://twitter.com/goloroden/status/1187470366475575301
