### ISSUE TITLE
Converting numbers other than “1” to “false”

### ISSUE THREAD

**Issue by Ohar** [thenativeweb/boolean#3]
I suppose it was done for some reason, but this reason is very unclear.

Is it bug or feature?

```js
boolean(1) // true
boolean(2) // false
```

If its a feature, why is it so?

You can see demo on [jsFiddle](https://jsfiddle.net/Ohar/nvj342yq/).

**Comment by goloroden** [comment]
I think this is a bug ;-)

Would you mind creating a PR?

**Comment by Ohar** [comment]
Okay, I will.
Thank you.

**Comment by Ohar** [comment]
Anyway, according to [tests](https://github.com/thenativeweb/boolean/blob/cd11086a4da002928a8a3329c8bfe8b0c78480b5/test/booleanTests.js#L167-L169) it was a planned feature.
