### ISSUE TITLE
Changelog missing 1.x and 2.x notes

### ISSUE THREAD

**Issue by bogdan-hubplanner** [thenativeweb/boolean#339]
Recently I've started working on a project that's badly outdated and  "boolean" is "^0.2.0" ... I would like to 'just upgrade it' but not sure what the implications are. 
Would be good if the changelog had some notes on any breaking changes.

**Comment by goloroden** [comment]
Apparently we only started in 3.x to run a changelog, so the only chance to recover what has changed is to look through the commits.

However, the changes shouldn't be too dramatic, given, that `boolean` is a pretty simple module.
