### ISSUE TITLE
Suggestion of not using value.trim()

### ISSUE THREAD

**Issue by fungiboletus** [thenativeweb/boolean#7]
https://github.com/thenativeweb/boolean/blob/f35f011f712ce036f334a608012cb1ecd6ba9151/src/boolean.js#L5

Is there a good reason to trim the string ? Could the following regex be used instead ?

```javascript
return /^\s*(true|t|yes|y|1)\s*$/i.test(value); 
```

**Comment by goloroden** [comment]
Hmmm, good question 🤔 

I will try to recover what the reason for trimming was, and then I'll get back to you.

**Comment by goloroden** [comment]
Okay… to be honest I don't know anymore why we did it like this.

So, yes, one could also use the regular expression you suggested, but I think that the version with `trim()` is more readable. Is there a special reason why you would prefer or suggest the regular expression?

**Comment by goloroden** [comment]
Okay, thanks for the explanation 😊

Then I think we‘ll leave it as it is (for the readability). But thanks a lot for the suggestion, anyway!
