### ISSUE TITLE
ON / on to true

### ISSUE THREAD

**Issue by edwinvdpol** [thenativeweb/boolean#8]
Hi,

Can you add the string "ON" and "on" to convert this to true?
Or is there a reason it shouldn't be?

Thanks!

**Comment by goloroden** [comment]
Hey @edwinvdpol :-)

Thanks for the suggestion, I definitely think this makes sense 👍 

I have just updated the code, and now `on` and `ON` work as well.
In addition, I have fixed that numbers not equal to `1` now return false (as they were intended to).

The updated code is available on npm as `1.0.0`.

**Comment by edwinvdpol** [comment]
Awesome, thanks!

**Comment by goloroden** [comment]
You're welcome 😊
