### ISSUE TITLE
2.0.0 and 2.0.1 release is broken!!! please unpublish it asap

### ISSUE THREAD

**Issue by niftylettuce** [thenativeweb/boolean#9]
the `main` entry is pointing to `"main": "build/lib/boolean.js",` however the only available file is `"main": "build/src/boolean.js",`

**Comment by niftylettuce** [comment]
also this package should export a default out of the box, we shouldn't have to use `.default` to use this... 🤦‍♂

**Comment by niftylettuce** [comment]
`npm unpublish boolean@2.0.0 && npm unpublish boolean@2.0.1`

**Comment by goloroden** [comment]
Thanks for the hint, `2.0.2` is on npm.

**Comment by niftylettuce** [comment]
@goloroden 	can you please export a default function so we don't have to do the non-standard practice of `require('boolean').default`?

**Comment by goloroden** [comment]
How would you do this? In https://github.com/thenativeweb/boolean/blob/fe1f93f146d30f39d6aa559010f6ba3e7ea366f0/lib/boolean.ts#L17 we already have a `default` export, but that's apparently not what you would suggest to do?

**Comment by niftylettuce** [comment]
something like this https://www.npmjs.com/package/babel-plugin-add-module-exports (also see https://www.typescriptlang.org/docs/handbook/namespaces-and-modules.html)

need to have `module.exports = boolean`

**Comment by goloroden** [comment]
WRT the more and more widespread usage of ES6 modules we wanted to get rid of module.exports and focus on the new keywords. 

Hence, we won’t introduce module.exports again. 

Since we are also not the only ones with this approach, I think we will leave it as it is. 

Of course, if you have an idea of how to combine both - the new syntax, an ES6 default export, and a way to use it in the old world - and come up with a PR, we are happy to discuss things.

**Comment by niftylettuce** [comment]
There are very very few with this approach in the community.  The latest LTS releases of Node don't even support the import/export... the only way possible is with transpiler like Babel.  I really am strongly against this approach.

I would recommend using Babel and transpiling a `lib` folder (similar to how you do now) but with `@babel/preset-env` and targeting Node v8.x or at the very least v10.x.

I do this similarly in projects where I want to use import/export or ES7 syntax:

See https://github.com/cabinjs/parse-app-info/blob/master/.babelrc, https://github.com/cabinjs/parse-app-info/blob/master/package.json#L32-L34, and <https://github.com/cabinjs/parse-app-info/blob/master/package.json#L108-L110>.

Ref: https://github.com/nodejs/Release#nodejs-release-working-group

**Comment by goloroden** [comment]
TBH, the result isn't worth the effort (introducing Babel, adopting and changing our build process, …). We build all of our modules in the same way, which means adjusting the build process for all of them – and we decided *not* to use Babel, but TypeScript, and go with ES6 modules.

Yes, you are right, Node does not yet support ES6 modules out of the box, but support is on its way.

I hardly doubt that adding a simple `.default` is that much of a problem, especially given that anyone who uses TypeScript, too, or who already uses ES6 modules does not have this problem. It's a legacy problem which will solve itself over time.

**Comment by niftylettuce** [comment]
I don't understand this trend of publishing packages to npm without pure JavaScript support.  I'm done here.

**Comment by goloroden** [comment]
It *has* pure JavaScript support, just the `require` is not in the way *you* like it. Sorry to say this, but if this is such a huge problem for you, feel free to fork it and change whatever you feel to be necessary.

Open-source is not just something that happens, there are people behind it who invest time and work. *Demanding* to change something, especially if it's not just a small thing, but includes the entire build process (where I explained to you that it affects lots of modules), without offering support is maybe a little bit … well, too much asked here 😉 

And while we're at it: Using three exclamation marks in the title, using `asap` in the title, not saying `Hello`, `Thanks` or anything else, and using the 🤦‍♂ emoji to comment our way of doing things doesn't help to improve our willingness to do as you demand. Sorry if this sounds harsh, but your tone was pretty rude right from the start, and except pointing out that the 2.0.0 release was broken (which I am thankful for) all you did was complaining about a really small thing.

So, to cut a long story short, as said: If this is *so* annoying for you, feel free to fork it and maintain a fork by yourself.

**Comment by niftylettuce** [comment]
I know a [little](https://github.com/niftylettuce) about open-source and time, and the npm community... I just don't agree with packages being published to npm that expect people to be using TypeScript or a syntax that's not even in Node core yet on LTS releases.  If it was in core, sure, why not.  You can lock this thread, but here's how Sindre uses TypeScript in ava and exports a default for example while still making CommonJS require work.

Ref: https://github.com/avajs/ava/blob/05f077e805bd1b3d58aa1e539d7e1e6a3f5c7042/lib/worker/main.js#L12-L21

**Comment by niftylettuce** [comment]
The reason for the exclamation marks and the word asap was because it was a package that was published to npm and broken, and has 100K downloads per week.  Otherwise if it was for anything else I wouldn't have done such a thing.  Thank you though for your help and time here.

**Comment by goloroden** [comment]
> The reason for the exclamation marks and the word asap was because it was a package that was published to npm and broken, and has 100K downloads per week.

Do you think we wouldn't have fixed this without these very pushy hints?

If, as you said, you know a little about open-source, then I guess you know that it's not only about technology, but also about empathy and working *together*, about respect and things like that. And I assume you can understand that this just feels *pushy* in the same way as if someone sends a mail with *importance high*.

And yes, we are still talking about something which is absolutely irrelevant for usage in plain vanilla JS. As said, feel free to fork and adopt.

Apparently, for 100k users this is not a major problem.

**Comment by niftylettuce** [comment]
Thank you @goloroden for your time and help here, I understand your points and thank you again.  If I decide to fork it I will keep your license and credit to you of course.  You can lock thread as well if you wish.
